import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Locale } from "../utils/i18n-config";
import { LanguageProvider } from "./components/provider/LanguageProvider";
import Navbar from "./components/UI/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: { lang: string };
}>) {
  const lang = await params.lang;
  return (
    <html lang={lang}>
      <body>
        <LanguageProvider>
        <Navbar />
        {children}
        </LanguageProvider>
      </body>
    </html>
  );
}
